//Campo de Request HTTP para teste da API

GET http://http://192.168.15.24:8080/rest/logins/all

###
POST http://192.168.0.18:8080/rest/logins/load HTTP/1.1
content-type: application/json

{   
    "login" : "Carlos",
    "senha" : "1234",
    "excluido":"nao"
}

###

POST http://192.168.0.18:8080/rest/logins/exclude HTTP/1.1
content-type: application/json

{
    "id"    : 4
}


###
GET http://192.168.0.26:8080/rest/pictures/all


###
POST http://192.168.15.34:8080/rest/pictures/load HTTP/1.1
content-type: application/json

{   
    "login" : "Carlos",
    "senha" : "1234",
    "excluido":"nao"
}

###
GET http://192.168.0.19:8080/rest/pictures/loadbyid/57
###
GET http://192.168.0.18:8080/rest/pictures/inicio


###
GET http://localhost:8080/api/login/


###

POST http://localhost:8080/api/login/ HTTP/1.1
content-type: application/json

{   
    "id"    : 1,
    "login" : "teste de edicao",
    "senha" : "1234"
}


###
GET http://localhost:8080/api/customview/detect


###

POST http://localhost:8080/api/define/ HTTP/1.1
content-type: application/json

{   
    "url" : "https://pyimagesearch.com/wp-content/uploads/2015/05/obama.jpg"
}



