# Generated by Django 3.0.3 on 2020-05-10 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('logdata', models.DateTimeField(auto_now=True)),
                ('exclude', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='picture_origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data64', models.TextField()),
                ('file', models.ImageField(upload_to='geo_entity_pic')),
                ('logdata', models.DateTimeField(auto_now=True)),
                ('exclude', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='test_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('exclude', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='picture_processed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='geo_entity_pic')),
                ('logdata', models.DateTimeField(auto_now=True)),
                ('exclude', models.CharField(max_length=3)),
                ('id_algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apimodule.algorithm')),
                ('id_picture_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apimodule.picture_origin')),
            ],
        ),
    ]
