# Generated by Django 3.0.3 on 2020-05-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimodule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture_origin',
            name='file',
            field=models.ImageField(upload_to='pic_file'),
        ),
    ]
