# Generated by Django 3.0.3 on 2020-05-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimodule', '0003_auto_20200510_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture_origin',
            name='file',
            field=models.ImageField(upload_to='imagens'),
        ),
        migrations.AlterField(
            model_name='picture_processed',
            name='file',
            field=models.ImageField(upload_to='imagens'),
        ),
    ]
