# Generated by Django 3.0.3 on 2020-05-10 19:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apimodule', '0004_auto_20200510_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture_origin',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('dccd88ba-a209-47a4-a7e8-421bc60d4a23'), editable=False),
        ),
        migrations.AlterField(
            model_name='picture_origin',
            name='exclude',
            field=models.CharField(default='nao', max_length=3),
        ),
    ]
