# Generated by Django 3.0.3 on 2020-05-10 19:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apimodule', '0005_auto_20200510_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture_origin',
            name='uuid',
        ),
        migrations.AddField(
            model_name='picture_origin',
            name='uu_id',
            field=models.UUIDField(default=uuid.UUID('8e273742-30da-4c0c-984b-f68ffaaec727'), editable=False),
        ),
    ]
