# Generated by Django 3.0.3 on 2020-05-11 02:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apimodule', '0006_auto_20200510_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture_origin',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='picture_origin',
            name='uu_id',
            field=models.UUIDField(default=uuid.UUID('98fe5df9-4707-4a07-8ff1-98b6772cf5b5'), editable=False, unique=True),
        ),
    ]
