# Generated by Django 3.0.3 on 2020-05-11 02:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apimodule', '0009_auto_20200510_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture_origin',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='picture_origin',
            name='uu_id',
            field=models.UUIDField(default=uuid.UUID('b8b13d65-3af5-4177-b44f-4f0f6bc14d4b'), editable=False, unique=True),
        ),
    ]
