# Generated by Django 3.0.3 on 2020-05-11 02:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apimodule', '0010_auto_20200510_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture_origin',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='picture_origin',
            name='uu_id',
            field=models.UUIDField(default=uuid.UUID('e99d2029-72ba-4866-a241-dde21ea28e47'), editable=False, unique=True),
        ),
    ]
